language: python
python:
    - "2.7"
    - "3.2"
    - "3.3"
    - "3.4"
    - "3.5"
    - "3.5-dev"
    - "nightly"

matrix:
    allow_failures:
        - python: "nightly"

# command to install dependencies
install: 
    - pip install -r requirements.txt

# command to run tests
script: 
    - ./run_tests.sh

after_success:
    - bash <(curl -s https://codecov.io/bash) 
